[theme]
primaryColor="#00B4D8"
backgroundColor="#0D0D11"
secondaryBackgroundColor="#1A1A24"
textColor="#FFFFFF"
[ui]
hideTopBar = true
[theme]
base="dark"

[browser]
# Встраиваем метатег верификации Яндекса прямо в заголовок HTML-кода хостинга
gatherUsageStats = false
